# Generated by Django 4.0.5 on 2023-03-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario1', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=50)),
                ('repepaswor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('tipousu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=100, null=True, verbose_name='Marca')),
                ('tipo', models.CharField(max_length=100, null=True, verbose_name='Tipo')),
                ('imagen', models.ImageField(null=True, upload_to='imagen/', verbose_name='Imagen')),
            ],
        ),
    ]
